spring:
  application:
    name: dispatcher-service

  lifecycle:
    timeout-per-shutdown-phase: 15s

  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-read-timeout: 5000
      request-connect-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 3
        initial-interval: 3000
        multiplier: 1:1
        max-interval: 5000

    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          group: ${spring.application.name}
        packlabel-out-0:
          destination: order-dispatched

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
